### PR TITLE
Slimstache

### PR DESCRIPTION
**Pull request by sars**
There is hamstache support in  hogan_assets
But many peoples and our company use slim in most of our projects.
I added similar slimstache feature to make templates with slim style

### CODE REVIEW

**Comment by leshill** [comment]
Hi @sars,

This looks good but needs to be cleaned up a bit.
- Needs a test
- Add slim as a development dependency to the `gemspec`

**Comment by sars** [comment]
Hi leshill
Test added, gemspec corrected.
Do you plan to support lib in future? e.g. when hogan.js will be updated...

**Comment by sars** [comment]
It is worked fine, but... i noticed a warning message: WARN: tilt autoloading 'haml' in a non thread-safe way; explicit require 'haml' suggested.
It raised in require_template_library method.
I do not quite understand how to solve it...

**Comment by leshill** [comment]
Hi @sars,

Thanks! Sorry for the delay! Just pulled this in and cut a new version!

**Comment by sars** [comment]
Thanks! good luck!

**Pull request merged**
